### ISSUE TITLE
Missing project description

### ISSUE THREAD

**Issue by simple10** [tjmlabs/ColiVara#110]
I just found this project from a related thread on Hacker News: https://news.ycombinator.com/item?id=42324059

It would be helpful to add a description, website, and topics to the project in Github Settings. This helps with project discovery and linking. The description is often used by bookmarking tools to create a title for the bookmark.

ColiVara looks impressive! I'm excited to try it out.

**Comment by Jonathan-Adly** [comment]
Thank you for bringing that up! I just added it - Appreciate it.
