### ISSUE TITLE
Huggingface space demo

### ISSUE THREAD

**Issue by Jonathan-Adly** [tjmlabs/ColiVara#115]

**Comment by HalemoGPA** [comment]
### Demo is done and open for changes. 
Check the current demo **[here: Colivara Demo](https://huggingface.co/spaces/Halemo/Colivara)**.
Future contributors can PR here: **[Colivara Demo PR](https://huggingface.co/spaces/Halemo/Colivara/discussions)**

**Comment by Jonathan-Adly** [comment]
Let's put its link on the homepage as discussed, then this issue can be closed!
