### ISSUE TITLE
Can you provide more details on how the `document_url` works behind the scenes?

### ISSUE THREAD

**Issue by steve-marmalade** [tjmlabs/ColiVara#123]
From [the docs](https://docs.colivara.com/getting-started/quickstart#index-a-document):
> We will also automatically take a screenshot of URLs (webpages) and index them.

And in the FAQ:
> We run a pipeline to convert them to images, and perform our normal image-based retrieval. This all happen for you under the hood, and you get the top-k pages when performing retrieval.

Can you provide a little more detail on this process?

- Is it a single image or are multiple "pages" created to capture all of the content on a large web page?
- If it's a single image, is it the full web page, or is it the portion visible in a pre-defined viewport size?

Thanks!

**Comment by Jonathan-Adly** [comment]
Hey Steve! 

We use Gotenberg under the hood: https://github.com/gotenberg/gotenberg/

This generates multiple pages for a large web page. Per this issue, this really can't be customized: https://github.com/gotenberg/gotenberg/discussions/381

If you have a specific feature or request in mind - happy to consider it.

**Comment by steve-marmalade** [comment]
Thanks for the quick response, that's exactly the context I was looking for!
