### ISSUE TITLE
Add Data extraction example as a notebook

### ISSUE THREAD

**Issue by Jonathan-Adly** [tjmlabs/ColiVara#62]

**Comment by Jonathan-Adly** [comment]
@Mai-Khuu  

See: https://github.com/tjmlabs/ColiVara-docs/blob/main/cookbook/data-extraction.ipynb

Close this issue when you are satisfied.

**Comment by Mai-Khuu** [comment]
Immensely helpful. thank you! 

The `extract_data` method is still magical to me. can you help me understand? 
I see a colivara `client` was created, along with an `llm_client`. From the result, I _know_ they work together to generate the result, but _where_ does that interaction happen? 

In other words, it's as if this piece of code works in silo to me, but it evidently doesn't: 
```python
    completion = llm_client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        response_format= { "type": "json_object" },
        temperature=0.25,
        seed=123
        )
```

Another question: 
```python
    messages = [
                    {"role": "system", "content": "Our goal is to find out when a policy was issued to remind our users to review it at regular intervals. Always respond in JSON"},
                    {"role": "user", "content": content}
    ]
```
How do these 2 messages work together? What does the role do? switching roles do not generate the correct result. 

Yet another question: 
If advanced filter is used, where does it fit into this cookbook?

**Comment by Jonathan-Adly** [comment]
The ultimate goal here is get the right **context** to the LLM, so it can do its job. (Answer questions, extract data, etc.) - that's what colivara does.

What does the LLM (GPT-4) expects: 
1. a base64 image (or images, but quality degrades after 10 or so images) 
2. instructions on what to do

What does the user have: 
1. A group of document - let's say a 10-50 documents of various sizes
2. A question or example data to extract 

So - our process is to take what the user have, and pass it to the LLM in the format that the LLM wants. Here are the steps:

1. Initialize the ColiVara client 
2. Get the relevant pages to the user question or data

- We can use the search endpoint (like the RAG example)
- We can get the document by name (like the data extraction)
- We can do advanced filtering and search (next example) 
- We can do advanced filtering alone (future TO DO)

It doesn't matter - the end results is the same. A group of pages, that are really base64 images (because that's what the LLM want). This is `doc` in the data_extraction example. `data = extract_data(data_to_extract, doc)`

3. Pass this to the LLM, which is the data_extraction does. Here is what the request to GPT4 should look like (reference: https://platform.openai.com/docs/api-reference/chat/create)

```
from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "What's in this image?"}, # the instruction to the model.
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://upload.wikimedia.org/<rest of url>.jpg", # or base64 
                    }
                },
            ],
        }
    ],
    max_tokens=300,
)

print(response.choices[0])
```
What we are doing in this extract_data function is basically constructing this example with our document with slight modifications. Let's go line by line:

1. string_json = json.dumps(data_to_extract) : we turn the user supplies example to a string - to pass this off in the LLM prompt as an example to follow
2. content = [  {# prompt here} ]  this is just the first element of the content array that the openAI client expects. Equivalent to `{"type": "text", "text": "What's in this image?"}` in their example above.
3. pages = colivara_document.pages - We got the document by name here, so we are getting the pages of the document. Important to note that if we search - we get the pages directly, so the RAG example is slightly different. 
4. for page in pages: -  here we loop through the document pages, and append to the content array. Again, the goal is to format an object in the format that OpenAI client expects. When we are done - our content array, would be in the same format as the content array that OpenAI clients wants.
5. messages = [ {system prompt}, {user prompt - aka our pages} ] - adding a system prompt is optional, but it helps to get the LLM to do what we want. 

Note here - from the perspective of the LLM, we are the user. So, that's why our pages is in a user role. 
6. completion = llm_client.chat.completions.create. Now that our pages and prompt are in the format that OpenAI expects, we are ready to call their API. And the model complies with our request.

**Comment by Mai-Khuu** [comment]
ah. Yes, I see it now. 
We append the url to the content, then use this content in the message, and pass that message to GPT!
Thank you for the detailed explaination
