### ISSUE TITLE
Updates to do with Update Embedding model 

### ISSUE THREAD

**Issue by HalemoGPA** [tjmlabs/ColiVara#83]
When embedding model is updated, embeddings of upserted documents should be updated.

**Comment by Jonathan-Adly** [comment]
Context for whoever comes across this - ColPali base model is ColQwen2, and there is is constant improvement and potential for the future model upgrades. 

If we store the embeddings today for document 1 on ColQwen2, then tomorrow we upgrade to ColQwen3. We should re-embed the documents on the new model to get the performance gain. (basically re-run upsertion).

**Comment by HalemoGPA** [comment]
@Jonathan-Adly 

E.g. Consider future users who would have documents embedded on the cloud using older embedding model. when they input query for search, it would use the new embedding model. Therefore it wouldn't be perfect in retrieval.

Proposed Solutions:
- with every update of model, all the cloud documents are re embedded or re-upserted.
or
- users use the older model for some time until we deprecate the model. and they would have to re upsert or re embed the documents.

**Comment by Jonathan-Adly** [comment]
We would go with option one. When we update the model, we would run a django management command to update the embeddings. It's on us to keep things SOTA.
